cluster_name     = "oficina-mecanica-cluster"
namespace_app    = "oficina-mecanica"
namespace_argocd = "argocd"
aws_region = "us-east-1"
bucket_name_kafka = "oficina-mecanica-kafka-history"
git_repo_url = "https://github.com/Grupo-SOAT/k8s-infra-oficina-mecanica"
git_target_revision_branch = "main"
git_manifests_path = "k8s"