cluster_name     = "oficina-mecanica-cluster"
namespace_app    = "oficina-mecanica"
namespace_argocd = "argocd"
aws_region = "us-east-1"
git_repo_url = "https://github.com/Grupo-SOAT/k8s-infra-oficina-mecanica"
git_target_revision_branch = "main"
git_manifests_path = "k8s"
ecr_repository_name_mnl = "registry-oficina-mecanica-mnl"
ecr_repository_name_ms_orcamentos = "registry-oficina-mecanica-ms-orcamentos"
image_tag_mutability = "MUTABLE"
ecr_scan_on_push = true
default_tags = {"ManagedBy" = "terraform"}
project_name = "oficina-mecanica"
database_user_secret = ""
database_password_secret = ""
jwt_secret = ""
api_key_chatbot = ""
spring_datasource_password = ""
spring_datasource_username = ""
default_user_password = ""
backend_url = "http://localhost:8080"
source_hash_code_lambda = ""
lambda_s3_key = ""
# TODO: preencher quando o RDS for provisionado no repo db-oficina-mecanica
database_host = ""
database_port = 5432
database_name = "workshop"
grafana_admin_password = ""