apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: oficina-mecanica
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:v1.7.0
          args:
            - --kafka.server=kafka-service:29092
          ports:
            - containerPort: 9308
              name: metrics
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: oficina-mecanica
  labels:
    app: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
    - port: 9308
      targetPort: 9308
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: oficina-mecanica
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  namespaceSelector:
    matchNames:
      - oficina-mecanica
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
