name: Deploy AWS Resources

on:
  repository_dispatch:
    types:
      - lambda-updated
      - db-deployed

jobs:

  deploy-infra:

    name: Deploy AWS Resources

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform on Runner
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15.6"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: Set Secrets for Terraform
        run: |
          echo "TF_VAR_database_user_secret=${{ secrets.POSTGRES_USER }}" >> "$GITHUB_ENV"
          echo "TF_VAR_database_password_secret=${{ secrets.POSTGRES_PASSWORD }}" >> "$GITHUB_ENV"
          echo "TF_VAR_jwt_secret=${{ secrets.JWT_SECRET }}" >> "$GITHUB_ENV"
          echo "TF_VAR_api_key_chatbot=${{ secrets.API_KEY_CHATBOT }}" >> "$GITHUB_ENV"
          echo "TF_VAR_spring_datasource_password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> "$GITHUB_ENV"
          echo "TF_VAR_spring_datasource_username=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> "$GITHUB_ENV"
          echo "TF_VAR_default-user-password=${{ secrets.DEFAULT_USER_PASSWORD }}" >> "$GITHUB_ENV"

      - name: Set Lambda Variables
        if: github.event.action == 'lambda-updated'
        run: |
          echo "TF_VAR_source_hash_code_lambda=${{ github.event.client_payload.lambda_hash }}" >> "$GITHUB_ENV"
          echo "TF_VAR_lambda_s3_key=${{ github.event.client_payload.lambda_key }}" >> "$GITHUB_ENV"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Clear Pending Secrets
        run: |
          SECRETS=(
            "oficina-mecanica/database-user"
            "oficina-mecanica/database-password"
            "oficina-mecanica/jwt-secret"
            "oficina-mecanica/api-key-chatbot"
            "oficina-mecanica/spring-datasource-password"
            "oficina-mecanica/spring-datasource-username"
            "oficina-mecanica/default-user-password"
          )

          for SECRET in "${SECRETS[@]}"; do
            DELETED=$(aws secretsmanager describe-secret \
              --secret-id "$SECRET" \
              --query "DeletedDate" \
              --output text 2>/dev/null || true)

            if [ -n "$DELETED" ] && [ "$DELETED" != "None" ]; then
              echo "Force-deleting pending secret: $SECRET"
              aws secretsmanager delete-secret \
                --secret-id "$SECRET" \
                --force-delete-without-recovery || true
            fi
          done

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var="database_user_secret=${{ secrets.POSTGRES_USER }}" -var="database_password_secret=${{ secrets.POSTGRES_PASSWORD }}" -var="jwt_secret=${{ secrets.JWT_SECRET }}" -var="api_key_chatbot=${{ secrets.API_KEY_CHATBOT }}" -var="spring_datasource_password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" -var="spring_datasource_username=${{ secrets.SPRING_DATASOURCE_USERNAME }}" -var="source_hash_code_lambda=${{ github.event.client_payload.lambda_hash }}" -var="lambda_s3_key=${{ github.event.client_payload.lambda_key }}" -var="default_user_password=${{ secrets.DEFAULT_USER_PASSWORD }}" -var="grafana_admin_password=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}"

      - name: Debug Terraform Outputs
        run: |
          terraform output

      - name: Configure kubectl
        run: |
          CLUSTER_NAME=$(terraform output -raw cluster_name)

          aws eks update-kubeconfig \
            --region us-east-1 \
            --name "$CLUSTER_NAME"

      - name: Wait for ALB
        run: |
          echo "Aguardando o ALB..."

          for i in {1..30}; do

            ALB_URL=$(kubectl get ingress workshop-backend-ingress \
              -n oficina-mecanica \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)

            if [ -n "$ALB_URL" ]; then
              echo "ALB encontrado:"
              echo "$ALB_URL"

              echo "ALB_URL=$ALB_URL" >> "$GITHUB_ENV"
              break
            fi

            echo "ALB ainda não disponível. Tentativa $i/30..."
            sleep 20

          done

          if [ -z "${ALB_URL:-}" ]; then
            echo "ERRO: ALB não foi encontrado."

            kubectl get ingress -n oficina-mecanica

            exit 1
          fi

      - name: Set Real Backend URL
        run: |
          echo "Backend URL: http://$ALB_URL"
          echo "TF_VAR_backend_url=http://$ALB_URL" >> "$GITHUB_ENV"

      - name: Terraform Apply Again
        run: |
          terraform apply -auto-approve -var="backend_url=http://$ALB_URL"

      - name: Set Database Variables
        if: github.event.action == 'db-deployed'
        run: |
          echo "TF_VAR_database_host=${{ github.event.client_payload.db_host }}" >> "$GITHUB_ENV"
          echo "TF_VAR_database_port=${{ github.event.client_payload.db_port }}" >> "$GITHUB_ENV"
          echo "TF_VAR_database_name=${{ github.event.client_payload.db_name }}" >> "$GITHUB_ENV"

          echo "Database host received: ${{ github.event.client_payload.db_host }}"
          echo "Database port received: ${{ github.event.client_payload.db_port }}"
          echo "Database name received: ${{ github.event.client_payload.db_name }}"


      - name: Run Terraform Apply after DB deployed for lambda values
        if: github.event.action == 'db-deployed'
        run: |
          terraform apply -auto-approve -var="database_host=${{ github.event.client_payload.db_host }}" -var="database_port=${{ github.event.client_payload.db_port }}" -var="database_name=${{ github.event.client_payload.db_name }}"
