name: Destroy AWS Resources

on:
  workflow_dispatch:

jobs:

  destroy-infra:

    name: Destroy AWS Resources

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Terraform on Runner
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15.6"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: Destroy Bucket Objects
        continue-on-error: true
        run: |
          set -e

          BUCKETS=(
            "lambda-code-archive-oficina-mecanica"
            "oficina-mecanica-kafka-history"
          )

          for BUCKET in "${BUCKETS[@]}"; do
            echo "=========================================="
            echo "Limpando bucket: $BUCKET"
            echo "=========================================="

            while true; do

              VERSIONS=$(aws s3api list-object-versions \
                --bucket "$BUCKET" \
                --query 'Versions[].{Key:Key,VersionId:VersionId}' \
                --output json)

              DELETE_MARKERS=$(aws s3api list-object-versions \
                --bucket "$BUCKET" \
                --query 'DeleteMarkers[].{Key:Key,VersionId:VersionId}' \
                --output json)

              OBJECTS=$(jq -n \
                --argjson versions "$VERSIONS" \
                --argjson markers "$DELETE_MARKERS" \
                '$versions + $markers')

              COUNT=$(echo "$OBJECTS" | jq 'length')

              if [ "$COUNT" -eq 0 ]; then
                echo "Nenhum objeto restante."
                break
              fi

              echo "Excluindo $COUNT objetos/versões..."

              echo "$OBJECTS" |
                jq '{Objects: .[:1000]}' |
                aws s3api delete-objects \
                  --bucket "$BUCKET" \
                  --delete file:///dev/stdin

            done

            echo "Bucket $BUCKET limpo com sucesso."
            echo
          done

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy all Resources
        run: terraform destroy -auto-approve
      
      - name: Destroy AWS secrets Brute force
        run: |
          aws secretsmanager delete-secret \
          --secret-id "oficina-mecanica/database-password" \
          --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/spring-datasource-username" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/api-key-chatbot" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/default-user-password" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/spring-datasource-password" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/jwt-secret" \
            --force-delete-without-recovery
          
          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/database-user" \
            --force-delete-without-recovery