name: Destroy AWS Resources

on:
  workflow_dispatch:

jobs:

  destroy-infra:

    name: Destroy AWS Resources

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Terraform on Runner
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15.6"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: Destroy Bucket Objects
        run: |
          sudo apt install jq

          export BUCKET="lambda-code-archive-oficina-mecanica"

          echo "Limpando o bucket: $BUCKET"

          aws s3api list-object-versions --bucket "$BUCKET" --output=json \
            --query='{Objects: append(Versions[].{Key:Key, VersionId:VersionId}, DeleteMarkers[].{Key:Key, VersionId:VersionId})}' | \
            jq -c '.Objects | select(. != null)' | while read -r batch; do
              # O S3 permite deletar até 1000 objetos por requisição
              echo "$batch" | jq -r 'chunk(1000)[] | {Objects: .}' | while read -r chunk; do
                aws s3api delete-objects --bucket "$BUCKET" --delete "$chunk"
              done
            done

          echo "Objetos excluídos com sucesso."


          export BUCKET="oficina-mecanica-kafka-history"

          echo "Limpando o bucket: $BUCKET"

          aws s3api list-object-versions --bucket "$BUCKET" --output=json \
            --query='{Objects: append(Versions[].{Key:Key, VersionId:VersionId}, DeleteMarkers[].{Key:Key, VersionId:VersionId})}' | \
            jq -c '.Objects | select(. != null)' | while read -r batch; do
              # O S3 permite deletar até 1000 objetos por requisição
              echo "$batch" | jq -r 'chunk(1000)[] | {Objects: .}' | while read -r chunk; do
                aws s3api delete-objects --bucket "$BUCKET" --delete "$chunk"
              done
            done

          echo "Objetos excluídos com sucesso."

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy all Resources
        run: terraform destroy -auto-approve
      
      - name: Destroy AWS secrets Brute force
        run: |
          aws secretsmanager delete-secret \
          --secret-id "oficina-mecanica/database-password" \
          --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/spring-datasource-username" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/api-key-chatbot" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/default-user-password" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/spring-datasource-password" \
            --force-delete-without-recovery

          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/jwt-secret" \
            --force-delete-without-recovery
          
          aws secretsmanager delete-secret \
            --secret-id "oficina-mecanica/database-user" \
            --force-delete-without-recovery