name: Destroy AWS Resources

on:
  workflow_dispatch:

jobs:

  destroy-infra:

    name: Destroy AWS Resources

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Terraform on Runner
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15.6"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: Destroy Lambda S3 Bucket
        continue-on-error: true
        run: |
          BUCKET="${{ vars.TF_LAMBDA_BUCKET }}"

          echo "Limpando bucket: $BUCKET"

          while true; do
            VERSIONS=$(aws s3api list-object-versions \
              --bucket "$BUCKET" \
              --query 'Versions[].{Key:Key,VersionId:VersionId}' \
              --output json)

            DELETE_MARKERS=$(aws s3api list-object-versions \
              --bucket "$BUCKET" \
              --query 'DeleteMarkers[].{Key:Key,VersionId:VersionId}' \
              --output json)

            OBJECTS=$(jq -n \
              --argjson versions "$VERSIONS" \
              --argjson markers "$DELETE_MARKERS" \
              '$versions + $markers')

            COUNT=$(echo "$OBJECTS" | jq 'length')

            if [ "$COUNT" -eq 0 ]; then
              break
            fi

            echo "Excluindo $COUNT objetos/versões..."

            echo "$OBJECTS" |
              jq '{Objects: .[:1000], Quiet: true}' |
              aws s3api delete-objects \
                --bucket "$BUCKET" \
                --delete file:///dev/stdin
          done

          echo "Excluindo bucket..."
          aws s3api delete-bucket --bucket "$BUCKET"

          echo "Bucket $BUCKET excluído."

      - name: Destroy Kafka History S3 Bucket
        continue-on-error: true
        run: |
          BUCKET="${{ vars.TF_KAFKA_BUCKET }}"

          echo "Limpando bucket: $BUCKET"

          while true; do
            VERSIONS=$(aws s3api list-object-versions \
              --bucket "$BUCKET" \
              --query 'Versions[].{Key:Key,VersionId:VersionId}' \
              --output json)

            DELETE_MARKERS=$(aws s3api list-object-versions \
              --bucket "$BUCKET" \
              --query 'DeleteMarkers[].{Key:Key,VersionId:VersionId}' \
              --output json)

            OBJECTS=$(jq -n \
              --argjson versions "$VERSIONS" \
              --argjson markers "$DELETE_MARKERS" \
              '$versions + $markers')

            COUNT=$(echo "$OBJECTS" | jq 'length')

            if [ "$COUNT" -eq 0 ]; then
              break
            fi

            echo "Excluindo $COUNT objetos/versões..."

            echo "$OBJECTS" |
              jq '{Objects: .[:1000], Quiet: true}' |
              aws s3api delete-objects \
                --bucket "$BUCKET" \
                --delete file:///dev/stdin
          done

          echo "Excluindo bucket..."
          aws s3api delete-bucket --bucket "$BUCKET"

          echo "Bucket $BUCKET excluído."

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"

      - name: Configure kubectl
        run: |
          CLUSTER_NAME=$(terraform output -raw cluster_name)

          aws eks update-kubeconfig \
            --region us-east-1 \
            --name "$CLUSTER_NAME"

      - name: Check EKS connection
        run: |
          echo "=== kubectl ==="
          kubectl get nodes

          echo "=== AWS EKS ==="
          aws eks describe-cluster \
            --name oficina-mecanica-cluster \
            --region us-east-1 \
            --query 'cluster.endpoint' \
            --output text

      - name: Destroy all Resources
        run: terraform destroy -auto-approve 
      
      - name: Destroy AWS secrets Brute force
        if: always()
        run: |
          SECRETS=(
            "oficina-mecanica/database-user"
            "oficina-mecanica/database-password"
            "oficina-mecanica/jwt-secret"
            "oficina-mecanica/api-key-chatbot"
            "oficina-mecanica/spring-datasource-password"
            "oficina-mecanica/spring-datasource-username"
            "oficina-mecanica/default-user-password"
          )

          for SECRET in "${SECRETS[@]}"; do
            aws secretsmanager delete-secret \
              --secret-id "$SECRET" \
              --force-delete-without-recovery 2>/dev/null || true
          done