alloy:
  configMap:
    content: |
      otelcol.receiver.otlp "default" {
        grpc { endpoint = "0.0.0.0:4317" }
        http { endpoint = "0.0.0.0:4318" }
        output {
          traces = [otelcol.exporter.otlp.tempo.input]
          metrics = [otelcol.exporter.prometheus.prom.input]
          logs = [otelcol.exporter.otlphttp.loki.input]
        }
      }
      otelcol.exporter.otlp "tempo" {
        client {
          endpoint = "tempo.observability.svc.cluster.local:4317"
          tls { insecure = true }
        }
      }
      otelcol.exporter.otlphttp "loki" {
        client {
          endpoint = "http://loki-gateway.observability.svc.cluster.local:80/otlp"
        }
      }
      otelcol.exporter.prometheus "prom" {
        forward_to = [prometheus.remote_write.prom.receiver]
      }
      prometheus.remote_write "prom" {
        endpoint {
          url = "http://kps-kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/write"
        }
      }
    create: true
  extraPorts:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
controller:
  type: daemonset
service:
  enabled: true
  type: ClusterIP
