persistence:
  enabled: true
  size: 10Gi
  storageClassName: gp3
tempo:
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 256Mi
  server:
    http_listen_port: 3200
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
